### ISSUE TITLE
Won't mount

### ISSUE THREAD

**Issue by totalitarian** [vKolerts/sidenoder#10]
Vert strange behaviour, when I click mount (or even use automount) the mount button turns orange and then red, signalling the mount is mounted. If however, I browse using the local option to `C:/Users/Archie/AppData/Local/Temp/mnt` the games list loads.

So mounting is working but sidenoder is not detecting it.

Log attach
[debug_last.log](https://github.com/vKolerts/sidenoder/files/7491967/debug_last.log)

**Comment by vKolerts** [comment]
Thank's, I will check it on Windows. I think it's happend because other rclone runned in parallel

**Comment by vKolerts** [comment]
Sorry, still can't catch this problem. I work on optimizations of mount process, maybe it will fix this issue in future too
