### ISSUE TITLE
Rclone failed on mount command

### ISSUE THREAD

**Issue by hchwa** [vKolerts/sidenoder#13]
![image](https://user-images.githubusercontent.com/6304345/144778738-dcda4a8d-8c0b-4fef-b00a-bacddff33f17.png)
When I run the program 1st time and I run into this issue. 

Please advise how I can troubleshoot this issue.

**Comment by KaladinDMP** [comment]
This is because you didn't follow the install instructions. It clearly shows you didn't install winsfp which is required to mount on windows. Get the new config at t.me/sidenoder

**Comment by hchwa** [comment]
@KaladinDMP Thank you much!!
