### ISSUE TITLE
rClone fails to mount on mac

### ISSUE THREAD

**Issue by midnight12346** [vKolerts/sidenoder#19]
Error: Command failed: "/Users/*user name*/sidenoder/rclone" cmount --read-only --rc --rc-no-auth --config="/Users/David_Hoover/Downloads/rclone.conf" VRP-mirror13: "/var/folders/y9/m0jr3lgn5cx5w8l69rzmf6fr0000gn/T/mnt"
2021/12/28 21:26:57 NOTICE: Serving remote control on http://localhost:5572/
2021/12/28 21:26:58 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed: cgofuse: cannot find FUSE

**Comment by KaladinDMP** [comment]
Does anyone bother to read other issues or the install instructions before posting "issues?"  You skipped the first step of installation on a mac which I assume you have from this error even though you didn't mention. https://github.com/vKolerts/quest-sidenoder#running-the-compiled-version

You must install osxfuse newest to perform mount. If you skip this step it doesn't have the proper dependencies to work correctly. 

I'm assuming this is the issue

**Comment by midnight12346** [comment]
> Does anyone bother to read other issues or the install instructions before posting "issues?" You skipped the first step of installation on a mac which I assume you have from this error even though you didn't mention. https://github.com/vKolerts/quest-sidenoder#running-the-compiled-version
> 
> You must install osxfuse newest to perform mount. If you skip this step it doesn't have the proper dependencies to work correctly.
> 
> I'm assuming this is the issue

sorry I'm blind i didn't see that sorry for wasting your time, my apologies
