### ISSUE TITLE
Cannot load anything on MacOS Monterey

### ISSUE THREAD

**Issue by minuz** [vKolerts/sidenoder#20]
Hi, I've been trying to use this app on my mac but it never connects to the Oculus device. When I start the app, I allow the connection on the headeset, but the statuses shown on the screenshot never changes.
![image](https://user-images.githubusercontent.com/818024/147844039-8435b895-414e-4245-a62c-243cf6f04ae5.png)

In addition, I believe there might some memory leak as if I keep waiting, eventually the app starts consuming a lot of computer resources until I'm forced to quit app. 

Any ideas or guidance on how to make this run? Any help is appreciated!

**Comment by KaladinDMP** [comment]
You're getting the RSA key computer connection popup or the data popup?
Only the RSA key popup is needed for sideloading. You get the data popup
regardless, even if dev mode is off or borked which is feel is your issue

**Comment by minuz** [comment]
Hey @KaladinDMP , thanks for your reply! I managed to get it to work. It seems I was reading an old doco that didn't have the osxfuse pre-requisite. Once I installed that, it started to mount. As for connecting to the device, I did what you suggested and toggled on/off the developer mode on the device and that fix the connection issue as well.
