### ISSUE TITLE
Source repo isn't tagged

### ISSUE THREAD

**Issue by mcohan** [vKolerts/sidenoder#22]
The source repo for this project is not tagged with your releases making it difficult to track changes.
Can you please sync them?

Also, why are you using a different repo for binaries vs just releases off of the source repo?

**Comment by mcohan** [comment]
I am not sure why my git client wasn't showing the tags, I see them clearly on the github UI!

I'll close this, but I'm curious why the split repos.

**Comment by vKolerts** [comment]
I am just preparing to close old repo
