### ISSUE TITLE
I can't get games list

### ISSUE THREAD

**Issue by 54whui** [vKolerts/sidenoder#26]
I use new version rclone and mounted success, now the program looks is ok.
But the remote windows has nothing.
I use rclone_ffa_271221.conf and rclone_all_271221.conf file.
In the config file the expire is 2021-11-09 : "expiry":"2021-11-09T19:01:42.8610979-05:00".
Please tell me how I can do?
![image](https://user-images.githubusercontent.com/28184886/150472668-3fbff85f-e827-4d73-b44f-d0b88905695e.png)

**Comment by 54whui** [comment]
My system is macos

**Comment by 54whui** [comment]
I get game list now. I'm download rclone file from https://rclone.org/downloads/ to replace the old version that copy from macos /usr/local/bin/rclone.
thanks a lot

**Comment by vKolerts** [comment]
Thanks. I found reason  https://github.com/vKolerts/sidenoder/issues/25#issuecomment-1018618845
