### ISSUE TITLE
"check mount for updates" non-functional

### ISSUE THREAD

**Issue by rossbeck** [vKolerts/sidenoder#27]
Hi, great app! 
I noticed that if you click on installed APPs and then "check mount for updates" button, it brings up a blank window with just a 'search' button that the top. When this is clicked, it appears to open a non-related search for the window underneath.  Just thought I'd let you know that the mount is not populating when trying to check for updates.

**Comment by vKolerts** [comment]
Hi, thanks. Check mount for updates worked for me. Remote must be mounted to worked mirror. Yes, I forgot about search at installed(

**Comment by rossbeck** [comment]
Hm, ok. I guess I was just trying to use it with a local directory (I manage my games/updates locally, not on a mirror). It doesn't seem to be working with a local directory.  Not a big deal, but figured you might want to know!
Thanks

**Comment by vKolerts** [comment]
You can make local folder like alias by rclone.conf (example https://wiki.vrpirates.club/resilio/rclone.conf) 

You need folder "Quest Games" at the root of this "remote" for updates checking
