### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by TheScreechingBagel** [vKolerts/sidenoder#29]
It is true that the MIT license allows you to do this, but it is really in bad taste.

**Comment by KaladinDMP** [comment]
You mean forking a dead program and improving it beyond anything that was ever done originally?

 I would say it's not against the devs wishes concidering he linked to the old repo. https://github.com/whitewhidow/quest-sidenoder#june-20-2021--unofficial-user-maintained-fork-available-here

Am I missing something? Plus concidering what's it's used for it seems only smart to me

**Comment by vKolerts** [comment]
At this time all sources at old repo. I has some own sense for not post at this state of sources for this repo. To my great regret, the release of the necessary changes is greatly delayed(((

**Comment by chrisdlees** [comment]
At least OP shows a _slight_ modicum of decorum. Most newbs just use Issues to inform the maintainers that their project sucks, to complain about a known bug (bonus points if the bug has a workaround in the README), or to demand pie-in-the-sky features that are hundreds of hours of coding away ( bonus points if it's already on the roadmap { double bonus if it has several blocking features on the roadmap [ TRIPLE bonus if they refer to the project's current state as "completely worthless/useless" ] } ) 

I think OP just isn't aware of the huge mess a large refactor can make out of a code tree, or that binary releases might contain secrets that haven't been tokenized/vault'd/CI'd yet.... Which  isn't _that_ much better, but an ignorant defense of FOSS w/ insult is better than no defense at all ;)

Finally, to OP: 


**_#~~ PROTIP ~~#_** 
> In the future, wait for the answer to your question first, _before_ making a snide remark. Then you can avoid looking foolish. Better yet, don't be snide towards any developer of non-commercial software **_at all!_**
