### ISSUE TITLE
Rclone failed on mount command

### ISSUE THREAD

**Issue by lNavigatoRl** [vKolerts/sidenoder#3]
Error: Command failed: "/Users/user/sidenoder/rclone" cmount --read-only --rc --rc-no-auth --config="/Users/user/sidenoder/rclone.conf" VRP_mirror10: "/var/folders/37/wjzhvq7x4ws_fskt6mpk76rw0000gp/T/mnt"
2021/10/28 20:25:32 NOTICE: Serving remote control on http://localhost:5572/
kext load failed: -603947007
mount_osxfuse: the file system is not available (255)
2021/10/28 20:25:32 ERROR : Google drive root '': Mount failed
2021/10/28 20:25:32 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed

v 0.7.2

**Comment by vKolerts** [comment]
> Error: Command failed: "/Users/user/sidenoder/rclone" cmount --read-only --rc --rc-no-auth --config="/Users/user/sidenoder/rclone.conf" VRP_mirror10: "/var/folders/37/wjzhvq7x4ws_fskt6mpk76rw0000gp/T/mnt" 2021/10/28 20:25:32 NOTICE: Serving remote control on http://localhost:5572/ kext load failed: -603947007 mount_osxfuse: the file system is not available (255) 2021/10/28 20:25:32 ERROR : Google drive root '': Mount failed 2021/10/28 20:25:32 Fatal error: failed to mount FUSE fs: mount stopped before calling Init: mount failed
> 
> v 0.7.2

You need to google this issue "mount_osxfuse: the file system is not available (255)" 
For example: https://github.com/Homebrew/homebrew-cask/issues/27293
