### ISSUE TITLE
[Feature Request] Add an installation queue.

### ISSUE THREAD

**Issue by b1bradders** [vKolerts/sidenoder#30]
When you install games through Remote, it has this button on the popup:
<img width="312" alt="Screenshot 2022-04-07 at 5 51 36 PM" src="https://user-images.githubusercontent.com/69256931/162256025-cb8185f4-944c-4ddb-80bc-eb866143a6c9.png">

Which, when pressed, closes that little popup. But I don't know if it's still installing. And, I would like to sideload/install multiple games/apps so a queue to show what's installing/happening to the currently installing game/app (in the background) and to see whats going to be installed next and a button to remove it from the queue.

**Comment by vKolerts** [comment]
I am working on it, but hasn't time for finish with main job 
![изображение](https://user-images.githubusercontent.com/69972136/168551512-0adf134e-9746-4733-b00e-532e07881bed.png)

ps: sorry for my english)
