### ISSUE TITLE
Can someone send me the VRP mirrors? I can't access Telegram.

### ISSUE THREAD

**Issue by b1bradders** [vKolerts/sidenoder#31]
Hi! I am trying to get the VRP mirrors but I can't download from Telegram. Could someone please provide me them?

**Comment by KaladinDMP** [comment]
> Hi! I am trying to get the VRP mirrors but I can't download from Telegram. Could someone please provide me them?

https://drive.google.com/file/d/1tj_LTF8C25lB_F-tsfUnXAooma_R_g9p/view?usp=drivesdk

Vrp mirrors are basically useless and mostly over quota but here's the "all config". This includes much better and more useful FFA mirrors as well. Download quickly as I don't believe the dev wishes configs to be posted to the GitHub or else he would provide them here. I will delete this file off my gdrive in 1 hour
