### ISSUE TITLE
Can't download any pc games

### ISSUE THREAD

**Issue by ghost** [vKolerts/sidenoder#5]
Says that the file is locked when I try to copy it to desktop, none of the PC games have a download button.

**Comment by vKolerts** [comment]
You can copy files from your shell file browser.  For easy way to open dir location you can click folder button left from dir location at navigation bar
![изображение](https://user-images.githubusercontent.com/69972136/139596030-2544bb64-8557-4f40-8936-46e59a6c3816.png)

**Comment by ghost** [comment]
> You can copy files from your shell file browser.
Gives me a io error when I copy it and paste it to my desktop or folders

**Comment by vKolerts** [comment]
switch the mirror or wait for mirror quota restart
